require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Allow ngrok (work hotspot dev)
  config.hosts << "drinkably-astable-libby.ngrok-free.dev"

  # In the development environment your application's code is reloaded any time
  # it changes. This slows down response time but is perfect for development
  # since you don't have to restart the web server when you make code changes.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable caching. By default caching is disabled.
  # Run rails dev:cache to toggle caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.cache_store = :memory_store
    config.public_file_server.headers = { "Cache-Control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
    config.cache_store = :null_store
  end

  # Store uploaded files on the configured storage service.
  config.active_storage.service = :amazon

  # Action Mailer
  config.action_mailer.perform_deliveries = true
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.perform_caching = false
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    address: "smtp.gmail.com",
    port: 587,
    domain: "gmail.com",
    user_name: ENV["GMAIL_SMTP_USERNAME"],
    password: ENV["GMAIL_SMTP_PASSWORD"],
    authentication: "plain",
    enable_starttls_auto: true
  }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise exceptions for disallowed deprecations.
  config.active_support.disallowed_deprecation = :raise

  # Tell Active Support which deprecation messages to disallow.
  config.active_support.disallowed_deprecation_warnings = []

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Keep Rails from printing the Ruby source line under every SQL query.
  #
  # Example noise this removes:
  #   ↳ app/controllers/v1/revenuecat/customers_controller.rb:190
  config.active_record.verbose_query_logs = false

  # Highlight code that enqueued background job in logs.
  # This is useful normally, but noisy during signup/email debugging.
  config.active_job.verbose_enqueue_logs = ENV["QUIET_MAILER_LOGS"] != "true"

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # Temporary debug helper:
  # Start Rails with QUIET_SQL=true when you want to hide ActiveRecord SQL noise
  # and only see your intentional custom debug logs like [RC_LINK].
  #
  # PowerShell:
  #   $env:QUIET_SQL = "true"
  #
  # Normal SQL logs come back when QUIET_SQL is not set to "true".
  if ENV["QUIET_SQL"] == "true"
    config.active_record.logger = nil

    config.after_initialize do
      null_logger = Logger.new(File::NULL)

      ActiveRecord::Base.logger = null_logger

      if defined?(ActiveRecord::Base.connection_pool)
        ActiveRecord::Base.connection_pool.connections.each do |connection|
          connection.instance_variable_set(:@logger, null_logger) if connection
        end
      end
    end
  end

  # Temporary debug helper:
  # Start Rails with QUIET_MAILER_LOGS=true when you want welcome emails to still
  # send, but you do not want ActionMailer/ActiveJob dumping the rendered email
  # and delivery details into the development log.
  #
  # PowerShell:
  #   $env:QUIET_MAILER_LOGS = "true"
  #
  # This does NOT disable welcome emails. It only quiets mailer logging.
  if ENV["QUIET_MAILER_LOGS"] == "true"
    config.action_mailer.logger = nil

    config.after_initialize do
      null_logger = Logger.new(File::NULL)

      ActionMailer::Base.logger = null_logger if defined?(ActionMailer::Base)
      ActiveJob::Base.logger = null_logger if defined?(ActiveJob::Base)
    end
  end
end